#.PHONY: demo1 demo2 demo3 demo4 demo5
demo1 : demo1.cpp
	g++ demo1.cpp -o demo1 -std=c++11 -pthread
demo2 : demo2.cpp
	g++ demo2.cpp -o demo2 -std=c++11 -pthread
demo3 : demo3.cpp
	g++ demo3.cpp -o demo3 -std=c++11 -pthread
demo4 : demo4.cpp
	g++ demo4.cpp -o demo4 -std=c++11 -pthread
demo5 : demo5.cpp
	g++ demo5.cpp -o demo5 -std=c++11 -pthread
clean :
	rm -f demo1 demo2 demo3 demo4 demo5
